"""Write theme/snippets/pp-temple-city.liquid from the stroke files' city lines.

The homepage marquee (sections/pp-temple-marquee.liquid) shows each temple's city
line under its art. The line lives in theme/assets/pp-temple-<slug>.json, but
Liquid cannot read an asset's contents, and fetching 45 stroke files in the
browser just for one line each would cost the shopper megabytes. So the lines
are copied into a snippet at build time. The snippet prints nothing for a slug
it does not know, which the marquee treats as "no drawing uploaded yet".

Re-run after adding a temple or rebuilding a stroke file:

    python scripts/temple_city_snippet.py
"""
import json
from pathlib import Path

THEME = Path(__file__).resolve().parent.parent / "theme"


def main():
    rows = []
    for path in sorted((THEME / "assets").glob("pp-temple-*.json")):
        slug = path.stem.removeprefix("pp-temple-")
        city = json.loads(path.read_text())["city"]
        rows.append(f"  when '{slug}'\n    echo '{city.replace(chr(39), '&#39;')}'")
    body = "\n".join(rows)
    out = THEME / "snippets" / "pp-temple-city.liquid"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "{%- comment -%}\n"
        "  City line for a temple slug, as printed under its art. Generated by\n"
        "  scripts/temple_city_snippet.py from assets/pp-temple-<slug>.json; do not edit\n"
        "  by hand. Prints nothing for an unknown slug.\n"
        "{%- endcomment -%}\n"
        "{%- liquid\n"
        "  case slug\n"
        f"{body}\n"
        "  endcase\n"
        "-%}\n"
    )
    print(f"{out.relative_to(THEME.parent)}: {len(rows)} temples")


if __name__ == "__main__":
    main()
